name: Test Code New

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '*md'
      - 'config.yaml'
  
  pull_request:
    branches: main
    paths-ignore:
      - '*md'
      - 'config.yaml'
 
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
      # Path to directory with code. Code coverage and code analysis will run on
      SRC_DIR: src      
      # Path to directory with (CI) tools or tests. Used for finding unit tests
      TOOLS_DIR: tools
      TESTS_DIR: tests
      REPORTS_DIR: docs/reports
      
jobs:
  test-code:
    if: github.run_number > 1
    name: Analyse and test code new
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest
          cache: true

      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: ${{ env.SRC_DIR }}
          select-by-folder: ${{ env.TESTS_DIR }}
          code-coverage: true
          code-coverage-format: cobertura
          code-coverage-output-file: ${{ env.REPORTS_DIR }}/codecoverage.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{ env.REPORTS_DIR }}/codecoverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '50 75'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
